### ISSUE TITLE
Reports of the Transmutation Table not working after use

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/Equivalent-Exchange#1]
I've not been able to reproduce this myself but we had a report over on the Neotech tracker original issue:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5366

After learning a few EMC'able blocks, transmutation table and tablet cannot learn/unlearn new blocks, You can take all learnt items out for free

**Steps to reproduce**
Create new world
Cheat in a transmutation tablet/table
Learn a few EMC'able blocks in the transmutation tablet/table
Close it and wait a bit
Try to learn a few more EMC'able blocks
Then it should not be possible to learn/unlearn blocks, items taken out will be free

**Expected behaviour**
Transmutation tablet/table do not stop learning items

they provided both debug and latest.logs

https://github.com/user-attachments/files/15937435/debug.log
https://github.com/user-attachments/files/15937436/latest.log

**Comment by FragsAreUs** [comment]
I have come across this issue as well. when it happens to me, I log out of the world and try to reload it but it would result in a crash

To note I was throwing high value emc items in mass. mostly diamonds and dark matter orbs but after leaving the table and opening it up again I noticed it stopped learning/unlearning blocks and was able to get items for free with the original bug report

[debug.log](https://github.com/user-attachments/files/15944674/debug.log)
[latest.log](https://github.com/user-attachments/files/15944675/latest.log)

**Comment by gigabit101** [comment]
not been able to reproduce this issue

**Comment by drasmart** [comment]
Huh... I thought the table didn't work at all.
Couldn't manage to learn a single item before.

Items just stayed in 'burn' slot.
If another stack was shift-clicked, the unburned items just get voided.

Tried again after seeing this issue (and related on Neotech pack).
Could put in the cobblestone, but eventually nothing else.
Logs: [[01_debug.log](https://github.com/user-attachments/files/16101992/01_debug.log)] [[01_latest.log](https://github.com/user-attachments/files/16101993/01_latest.log)]

Restarted. Managed to learn few things before issue appeared.
Logs: [[02_console.log](https://github.com/user-attachments/files/16102006/02_console.log)] [[02_debug.log](https://github.com/user-attachments/files/16102007/02_debug.log)]
Video capture: [[NeoTech_EE4_table_640_320_8.webm](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/60691a35-60ad-42e9-aac9-c62e8b94ca9f)]

Hope it helps.

**Comment by gigabit101** [comment]
This might have also been fixed with the changes made in 1.0.5, Still not able to reproduce the issue

**Comment by gigabit101** [comment]
Do let me know if the issue continues, maybe a copy of their world will help me track the issue down

**Comment by drasmart** [comment]
>This might have also been fixed with the changes made in 1.0.5, Still not able to reproduce the issue

With [[equivalentexchange-1.20.4-1.0.5-neoforge.jar](https://www.curseforge.com/minecraft/mc-mods/equivalentexchange/files/5504219)] the items are burned, EMC increased, but learned items do not appear immediately, have to switch pages.

Video capture: [[NeoTech_EE4_table_2.webm](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/cfd9a8c1-52a5-4025-9e90-9546e569e766)]

Logs: [[debug.log](https://github.com/user-attachments/files/16110371/debug.log)] [[latest.log](https://github.com/user-attachments/files/16110375/latest.log)]

World backup _(from before manual update of the mod from 1.0.3 to 1.0.5)_ :
🌐 https://drive.google.com/file/d/1r2fXZHBZ9rnixc7CTajo7qpDu_xkPW6A/view?usp=sharing

**Comment by gigabit101** [comment]
interesting, well at least it's working for you now, let me take a look at why it's not updating when learning new items

**Comment by gigabit101** [comment]
I found the issue, Fixed in 1.0.6 (Will be on CurseForge soon) but for now https://transfer.ch.tools/TcUFb/equivalentexchange-1.20.4-1.0.6.jar

**Comment by drasmart** [comment]
Couldn't load the world with 1.0.6 above, but the original issue is still present on 1.0.5 .
Logs: [[debug.log](https://github.com/user-attachments/files/16111617/debug.log)] [[latest.log](https://github.com/user-attachments/files/16111622/latest.log)]
![2024-07-05_11 36 37](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/b2f06551-fa85-4e3b-9b32-3b9083facc6e)

**Comment by gigabit101** [comment]
Thanks for the copy of the world that allowed me to track down the issue, It looks like your knowledge.dat file has become corrupt (This is something new for me to look into) for now just remove the "ftb neotech\saves\SurviTech2000\ftbteams\knowledge\*.dat" file and reload the save and it will be fine

**Comment by gigabit101** [comment]
I will keep your world file on hand to track down what caused this issue.

**Comment by gigabit101** [comment]
Also, 1.0.6 is now on CurseForge for you to download, apparently, I was dumb earlier and sent the wrong file... Hope this helps

**Comment by drasmart** [comment]
Removed .dat file.
Updated to 1.0.6 .

And it did work till it stopped.

Logs: [[debug.log](https://github.com/user-attachments/files/16112032/debug.log)] [[latest.log](https://github.com/user-attachments/files/16112033/latest.log)]

![2024-07-05_12 30 19](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/496ef6b6-6734-455d-b615-bc053cfef23d)

I believe I only interacted with the two leftmost barrels in the topmost row of the storage wall.
Succeeded in learning all EMC-able items from the first one.
Moved to the second one and somewhere then the bug hit again.

**Comment by gigabit101** [comment]
Yup was able to reproduce the issue with your world, I think I have fixed the issue and added some extra debug code around that section for if it happens again, expect a new build soon

**Comment by FragsAreUs** [comment]
> > I have come across this issue as well. when it happens to me, I log out of the world and try to reload it but it would result in a crash
> > To note I was throwing high value emc items in mass. mostly diamonds and dark matter orbs but after leaving the table and opening it up again I noticed it stopped learning/unlearning blocks and was able to get items for free with the original bug report
> > [debug.log](https://github.com/user-attachments/files/15944703/debug.log) [latest.log](https://github.com/user-attachments/files/15944704/latest.log)
> 
> This is an immersive engineering crash "Caused by: java.lang.NullPointerException: Cannot read field "tickCount" because "blusunrize.immersiveengineering.client.ClientUtils.mc().player" is null "

I am sorry for that, thought it was something related to EE4, but when this new build gets released I will make sure to test it. thank you for your time into looking into this issue <3

**Comment by drasmart** [comment]
Learning seems to work in 1.0.7 (though I didn't pay much attention to it, just checked at the end of a pretty long session).

But the

> You can take all learnt items out for free

part is still present on 1.0.7 :

| when | screenshot | EMC effect |
|--|--|--|
| before extaction attempt | ![2024-07-07_16 51 17](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/cfb76302-e77e-4147-ad48-c2f883140df1) |  |
| item picked up (still held with mouse) | ![2024-07-07_16 51 27](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/1aa64279-ae94-4191-9412-3cd94905e3c5) | :warning: EMC not decreased |
| placed back in 'burn' slot | ![2024-07-07_16 51 36](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/dfc5c4f0-1c7c-4616-a61e-9790f9593777) | :warning: EMC increased compared to before-extraction |
| shift-clicking out learned items works fine | ![2024-07-07_16 51 54](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/1182b726-00e8-4f4d-ab51-7970598989b5) | :white_check_mark: EMC decreased as expected |
| Learning new items is not (yet?) prevented | ![2024-07-07_16 53 20](https://github.com/FTBTeam/Equivalent-Exchange/assets/5711520/3b129739-9f4c-4a39-84da-9cad6cd08581) | :white_check_mark: EMC increased as expected |

Logs: [[debug.log](https://github.com/user-attachments/files/16120772/debug.log)] [[latest.log](https://github.com/user-attachments/files/16120773/latest.log)]

**Comment by whydisnec** [comment]
Was just about to post this myself, been having the same issues in NeoTech. I also noticed some other weirdness with the transmutation GUI, like "ghost items" being created when scrolling through pages, which can be deleted by clicking on them.

_Normal Screen_
![Normal Screen](https://github.com/FTBTeam/Equivalent-Exchange/assets/131700287/991e4f8a-7887-47b8-8735-413f562c61cf)

_Next page shows duplicate cobblestone walls_
![Duplicate cobblestone walls](https://github.com/FTBTeam/Equivalent-Exchange/assets/131700287/9778595d-6d5a-4bdf-998c-3644009017af)

_Clicking the duplicate deletes it and leaves an empty slot, nothing happens to EMC_
![Duplicate middle cobble stairs are deleted](https://github.com/FTBTeam/Equivalent-Exchange/assets/131700287/0c6b3afb-c286-4f1e-8560-c6fb08382236)

_Same is true if you keep scrolling through pages, items will keep showing up and disappear when interacted with_
![Deleting a bunch of stuff](https://github.com/FTBTeam/Equivalent-Exchange/assets/131700287/acbf74b9-baf6-42e0-ad33-49600c380db4)

Also, logs keep showing multiple errors in a row whenever a table(t) is opened "Player tried adding item 0 minecraft:air to transmutation inventory with no emc value", is that normal/related?
